export const APP_NAME = 'MyJob';

export const LOGO_IMAGE = {
  lightLogoSmall: require('../assets/images/logo/light-logo-small.png'),
  lightLogoMedium: require('../assets/images/logo/light-logo-medium.png'),
  lightLogoLarge: require('../assets/images/logo/light-logo-large.png'),
  darkLogoSmall: require('../assets/images/logo/dark-logo-small.png'),
  darkLogoMedium: require('../assets/images/logo/dark-logo-medium.png'),
  darkLogoLarge: require('../assets/images/logo/dark-logo-large.png'),
};

export const IMAGES = {
}

export const COLOR = {
  myJobCustomColors: {
    white: '#FFFFFF',
    black: '#000000',
    bluePurple: '#0D0040',
    purpleBlue: '#0D0140',
    bobel: '#B0B0B0',
    blueGrey: '#60778C',
    cloud: '#C4C4C4',
    lavenderMist: '#E6E1FF',
    greyChateauBluePurple: '#A9A5B8',
    darkIndigo: '#130160',
    moonrakerPurplyBlue: '#D6CDFE',
    mulledWineBluePurple: '#514A6B',
    desertStorm: '#F8F8F8',
    lightApricot: '#FED5AD',
    gunPowderPurplyBlue: '#3F3D56',
    platinum: '#E4E4E4',
    melon: '#FFB6B6',
    tuna: '#2F2E41',
    mistBluePurplyBlue: '#69687F',
    neonCarrot: '#FCA34D',
    haitiBluePurple: '#150B3D',
    artyClickUltramarine: '#3F13E4',
    deepSaffron: '#FF9228',
    mercury: '#E6E6E6',
    porcelain: '#F2F2F2',
    ghostPurpleBlue: '#CBC9D4',
    burningOrange: '#FF6B2C',
    blueLotus: '#7551FF',
    santaGrey: '#A49EB5',
    moonrakerBluePurple: '#D6CCFE',
    frenchPass: '#AFECFE',
    paleViolet: '#BEAFFE',
    seashell: '#F2F1F1',
    artyClickRed: '#FF0000',
    lavenderPinocchioCyanBlue: '#DDE1E6',
    limedSpruce: '#3B4657',
    elephant: '#0C3548',
    vividTangerine: '#FF9E87',
    amethystSmoke: '#9D97B5',
    earkIndigo: '#140261',
    greyCloud: '#B5B6B7',
    lightRed: '#FF464A',
    geraldine: '#FF8588',
    roseMadder: '#E5252A',
    lightCarminePink: '#ED676A',
    azure: '#03A9F4',
    sandyBeach: '#FFEACC',
    butterscotch: '#FFB237',
    zinnwalditeBrown: '#2F0F08',
    roseWhite: '#FFF6F4',
    mediumSeaGreen: '#39B070',
    lightRose: '#FACACA',
    brightGrey: '#3A3451',
    dullLavenderBluePurple: '#A992FF',
    darkGrey: '#36343C',
    whiteSmoke: '#F5F5F5',
    darkPink: '#E94D8A',
    ebonyClay: '#232C3A',
    purpleHaze: '#423172',
    lavenderPurple: '#8979B7',
    purpleMonster: '#3F2686',
    lapisBlue: '#262F8C',
    paleGrey: '#FDFDFD',
    cloudOrangyRed: '#CCC3C1',
    sundownRed: '#FFB2B2',
    veryLightPink: '#FFF5F3',
    rubberDuckyYellow: '#FFD500',
    onyx: '#141414',
    mistBlue: '#6F6B80',
    purplishGrey: '#6F6A7F',
    oldLace: '#FFF4E9',
    gunmetal: '#2C363B',
    greyChateauCyanBlue: '#9FA7B1',
    martini: '#A6A6A6',
    palatinateBlue: '#3847E5',
    haiti: '#150A3C',
    davyGrey: '#5B5858',
    greyChateau: '#A7A7A7',
    lavenderPinocchioTealishBlue: '#DEE1E7',
    lavaRed: '#ED1C24',
    smalt: '#103793',
    downriverTealishBlue: '#081D58',
    coolGrey: '#9D9EA8',
    saffronMango: '#FFC367',
    downriverBlue: '#141B5D',
    ultramarineBlue: '#5665FF',
    carbonGrey: '#5B5B5B',
    periwinkleBlue: '#939DFF',
    persianPink: '#FF82CB',
    silverChalice: '#AAAAAA',
    irishGreen: '#04B015',
    nebula: '#D0DBE0',
    sweetPink: '#FDA4A4',
    mirage: '#0F1728',
    leafyGreen: '#4DC132',
    mulledWine: '#524B6C',
    blueZodiac: '#141A52',
    peachSchnapps: '#FFE0D9',
    monsoon: '#898989',
    deepSapphire: '#19206E',
    venus: '#8982A2',
    dullLavender: '#A993FF',
    gainsboro: '#DCDCDC',
    ghostBluePurple: '#CBC8D4',
    gunPowderTealishBlue: '#3C4758',
    zombieGreen: '#56CD53',
    riverBed: '#3D4859',
  },
};

export const FONTS = {
  dMSansBold: 'DMSans-Bold',
  dMSansBoldItalic: 'DMSans-BoldItalic',
  dMSansItalic: 'DMSans-Italic',
  dMSansMedium: 'DMSans-Medium',
  dMSansMediumItalic: 'DMSans-MediumItalic',
  dMSansRegular: 'DMSans-Regular',
};

export const SHADOWS = {
  myJobCustomShadows: {
    0: {
      shadowColor: 'rgba(153, 171, 198, 0.6)',
      shadowOffset: {
        width: 4,
        height: 62,
      },
      shadowOpacity: 0.18,
      elevation: 15,
    },
  },
};

export const CONFIG = {
  initialColorMode: 'light',
};
